version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: nunatak_db
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: nunatak
      MYSQL_USER: nunatak
      MYSQL_PASSWORD: nunatak
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
